#
# Copyright (C) 2018-2019 The LineageOS Project
#
# SPDX-License-Identifier: Apache-2.0
#

BOARD_VENDOR := oneplus
DEVICE_PATH := device/oneplus/hotdogg
PRODUCT_SOONG_NAMESPACES += $(DEVICE_PATH)

# Kernel
TARGET_PREBUILT_KERNEL := device/oneplus/hotdogg/prebuilt/Image.gz-dtb

# Partitions
BOARD_BOOTIMAGE_PARTITION_SIZE := 100663296
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 100663296
BOARD_USERDATAIMAGE_PARTITION_SIZE := 115601780736
BOARD_DTBOIMG_PARTITION_SIZE := 16777216
BOARD_FLASH_BLOCK_SIZE := 262144
BOARD_ODMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_PRODUCTIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_SYSTEMIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_VENDORIMAGE_FILE_SYSTEM_TYPE := ext4
TARGET_COPY_OUT_PRODUCT := product

#Init
TARGET_INIT_VENDOR_LIB := libinit_oneplus7t
TARGET_RECOVERY_DEVICE_MODULES := libinit_oneplus7t
TARGET_PLATFORM_DEVICE_BASE := /devices/soc/

# Recovery
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/etc/fstab.qcom

